### ISSUE TITLE
'Barcode is not available' error

### ISSUE THREAD

**Issue by yj-kwon** [isonet/angular-barcode#7]
At first, I used angular-barcode module as 1.2.5 version.
Today, I update as 1.4.2 version, I can see below error sentence in console

>Module 'barcode' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

So. I down-graded it as 1.2.5. That version is working well.
I use this module by using below step.
```
npm install --save angular-barcode
angular.module('MyExampleApp', ['barcode']);
```
Please check about it.
If you want to know other informs. Please comments.
Thanks.

**Comment by isonet** [comment]
Hey,

I'm sorry, I made a mistake when publishing the latest version, it should have been a major version since it includes a breaking change.
The new version 2.0.0.
Please check out the readme and the example/index.html file, there have been some changes. I renamed the package to angular-barcode to be more consistent with the different names.

So you can use this module like this:
`angular.module('MyExampleApp', ['angular-barcode']);`

**Comment by isonet** [comment]
I also added a demo at: https://isonet.github.io/angular-barcode/

**Comment by yj-kwon** [comment]
@isonet 
Thank you for your help.
I can use this 1.4.2 version by using 'angular-barcode' instead of 'barcode'.
And your demo link is so useful my job.

**Comment by isonet** [comment]
No problem!
